name: Remote SSH Command

on: [push]

jobs:
  deploy:
    name: Building CD pipeline
    runs-on: ubuntu-latest
    steps:

    - name: Checkout codee
      uses: actions/checkout@v2

    - name: Execute CD pipelinee
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: 62.72.30.103
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY_VPS }}
        port: 22
        script: |
          cd react-deploy/client
          git pull origin master
          npm install
          npm run build
          pm2 serve build 3000 --name react-app --spa
