name: Remote SSH Command

on: [push]

jobs:
  deploy:
    name: Building CD pipeline
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute CD pipeline
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: 62.72.30.103
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY_VPS }}
        port: 22
        script: |
            cd react-deploy && cd client && git pull origin master && npm install && npm run build && npm run dev