name: Remote SSH Command
on: [push]
jobs:
  build:
    name: Building CD pipeline
    runs-on: ubuntu-latest
    steps:

    - name: checkout the code
      uses : actions/checkout@v2

    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1.2.0
      with:
          host: 62.72.30.103
          username: ubuntu
          password: ${{ secrets.PRIVATE_KEY_VPS }}
          port: 22
          script: ./deploy.sh